channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==1.26.4
      - pandas
      - matplotlib
      - scipy
      - statsmodels
      - scikit-learn
      - gradio
      - langchain
      - langgraph==0.3.18
      - langchain-openai
      - langchain-anthropic
      - langchain-ollama
      - langchain-community
      - openai
      - beautifulsoup4
      - lxml
      - tqdm
      - seaborn
      - networkx
      - requests
      - pyyaml
      - jupyter
      - notebook
      - ipykernel
      - pytest
      - transformers
      - sentencepiece
      - mcp
      - tooluniverse
      - python-dotenv
      - FlowKit
      - rdkit
      - scanpy
      - langchain_anthropic
      - langchain_community
      - langchain-google-genai
      - langchain_ollama
      - langchain_upstage
      - langchain_mistralai
      - langchain_aws
      - langchain-xai
